# Source material https://babel.hathitrust.org/cgi/pt?id=uc1.a0013865688;view=1up;seq=5

KALEV = ['Eestiaste kuulsam ennemuistene jut Kalewi poeast astub siin laiale piilu', 'tuttu. ',
         'ja laulu-söna riismetest koku korjaiud ja uest jalule seaiud rahwa ette, uutele euamist lül üks tundmata wödras aga ﬁiski on ta sündind oma küla  tups. ',
         'toob meile sonumid wanemast aeast, näitab meie sugumanemate elust ja waimu iwaliku märsisi, luba nemad kuulsat juttu olid sünniianud. ',
         'Aastate saead on läinub,rasked soa kurnad, tallu surmab, nälja piinad ja orja kütked olid kiil puhul rahwast muljunud ja maad mõne korra tühendanud. ',
         'aga köik need ed ei jdudnud mälestust mitte inimeste meelest kustutada, mis kaugemast õnne Kalewi poea päiwist üle oli jäänud. ',
         'Kui palju tema elust ja tegudest töﬁ on, ja lui palju laulikute meele mölgutused sirma körwa iluks uub. ',
         'selIega ei ole meil siiu pikemalt iegemist. ',
         'Arwamisel wdiks kül lugu ihe wana inimesega olla, kellel endine lapse pöli üsna dnnelikum ja parem ui praegune aeg, seal oli päike heledamast paistnud, taewas selgem ja maapind am olnub räägib mauaraul, ehk kül idielikult wäljaspoolt asjadest midagi oluub, waid et aga waatajal süda ja silm noorusel palju selgemad olid. ',
         'sa rahwa sugudel ükskord nende noor pöli vluub, mis hiljemine kui kuldne mälestuses läigib. ',
         'ehk kiil neil,  kes kiidetut aeal elasiwad ja asju toimetaﬁd, zused mured ja waewad kanda olidkui meilgi. ',
         'Ainuke wahe wöis ses olla,  kangus mehe  kuulsaks tegi, kudas nüüd waimu anded teda ülendawad. ',
         'päiwil on asjade lugu köigelt poolt hoopis teiseks läinud, meie olemertius n [ii-bi täielikumale Jumala tundmisele jöudnud, ka muidu mbnes tükis ss sacmub, sellepärast ei wöi meil wana aeg mitte enam nii kallis olla, seitse sada aastat enne meid siin elasimab, ja kellel töewalguse koitu weel ud selitanud. ',
         'Seepärast oleks suur rumaluss, sui kedagi pimedat ebausu iäwal ülemaks tahaks liita, sui seba, mis tal praegu käes on. ',
         'Aga ieiselt  ie mitte wähem rumalus, kui meie tühja uhkuse päralt seda lähekﬁme  suguwanemate mälestustest meie päiwini on ulatanud. ',
         'Teistel targesugudel leiti juba möne tuhat aasta eest kirja tundjaidkes tähtsaid juha pdlwele oskaﬁwad üles panna. ',
         'Soowitnieks. ', 'Lena mulle kannelt, Wanemuine. ',
         'Mis mina kodu nurmelt noppinud, Kaunis lugu mölgub meeles, Muistese pölwe pärandusest Ihkan laulu ilmutada. ',
         'Arkage, hallid muistena healed. ', 'Söudke sala jönumida, Parema pääwade paeatut, Armama aegade ilust. ',
         'Tule ja, lauliku targa tütar. ', 'Jöua Endla järweesta. ',
         'Pikalt ju höbedases peeglis Sidi hiuksid silitasid. ', 'Wötkem töe woli, wanad warjud. ',
         'Näitkem kadunud nägusi, Wahwama meeste ja nöidade Kalewide käikisida. ',
         'Lendagem lustina löuneela, Paari jammu pöhja poole, Kus neid kasusi kanarpikus, Wösu öitseb wööral wäljal. ',
         'Kaugelt wööral wäljal künnud, Mis mulle toonud tuule hoogu, Laened lustil weeretanud. ',
         'Mis mina kaua kaisula kannud, Pöues peidula pidanud, Mis mina kaljul kotka peas Ammust aega ellast audund. ',
         'Seda ma lauluna löksutelen Wööra kuuliate körwa. ',
         'Armamad kewadised kaimud Warisenud mulla alla, Kuhu mu lustina lööritusi, Kurwastuse kukkutusi, Ihkawa meele igatsusi Koolja kuulmesse ei kosta. ',
         'Üksina lindu laulan ma lusti, Kukkun üksi kurba kägu, Healiten üksi igatsusi, Kunni närtsin nurmedela. ',
         '"hwi muiste mälestust, Kalewide kuulutusi Kalmut künkast kerkimaie, Udu aurust paijumaie, Amarikust ärkamaie, Kanarpikut kaswamaie, Sambla joosta suitemaie. ',
         'Kussa warjud waikuela, Pikad pinad peituela, Kurnatused kaane alla Pörmu pöues poönutawad, Ukko hölmas uinutawad, Maarja rüppesa magawad. ',
         'Päike neid ei paistemaie, Kägu kuldne kukkumaie, Pesilindu petemaie Enam pease mätta alla. ',
         'Kuu aga kumab körgeelta, Täh tede silmad taewa sörwast Walgust warju walwajale, Kuma kuju kudujale. ',
         'Kes neid rahu rüüdidese, Warju waipa mähkinese Koolja koea katawada, Magajaida matawada. ',
         'Tuleb hoogult tuule tuhing, Kostab kaugelt laente kohin. ',
         'Toogu tulles terwisida, Kuulutagu kallimaida Unustuse uinund asju, Möttest läinud mälestusi,. ',
         'Mis ehk ehawalgel wälgub, Widewiku wilul wilgub, Kaste kergil keeritelles, Udu hölmal hüpeldelles. ',
         'Kuhu waimu äbarikud Amarasse ärgutanud, Sagarase seltsitanud, Parwes eha palistusel Ööde wilul öilmekarwa Mälestusi mängitawad, Kuldast kuulu keerutawad. ',
         'Waata mängt, wennikene, Näe ja keerdu, neitsikene, Nöua öudeid, söbrakene, Söna söudeid laulikule. ',
         'Mis kui koidul kirutelles, Pääwa piril pilutatud Usin unenägu kaub. ',
         'Löukene lööritelles, Künnitindu löksatelles, Kulla kägu kukkutelles Öö ja önned meta wiib. ',
         'Kiret kauwad meie pääwad, Tuhatnelja elu tunnid Ruttes Kalmu küngastele, Lendes rahu lepikusse, Kolletawa koolja ängi. ',
         'Kaduwal ei kodupaika, Rändajal ei rahurünka Pörmu pölwesta pärida. ',
         'Tuule tuhing tuiskas wile Laane ladwil laulemaie, Piki puida puhumaie, Mööda metsi möuramaie. ',
         'Sundis suwel söudewaida Lehekesi lehwimaie, Käskis kaske kahiseda, Haawa lehti argelikult  Warga küüsil wabieda, Rööwli kohkel kabieda. ',
         'Ohul helid örnad healed, Panid parmu pörisema, Pihulase piriema, Werewenna wirijema, Sitika siriemaie. ',
         'Liblik üksi, lustilindu, Tallab tuulta salamahti. ',
         'Köigis kuuleb targa körwa,  Möisteliku örna meele Lustilugu, leinanuttu, Kiutatuse kiljatusi, Kuuleb köigis muiste köne, Märkab muiste möistatusi, Sala söna sölmitusi. ',
         'Rööm ja mure kakikwennad, Kaksiklapsed loomuskoeas, Könniwad käsi käessa, Rändawad jammu jammusa. ',
         ' üks neid isa sünnitanud, Emä üks neid imetanud, ühes käkis kiigutanud. ',
         'Ehapuna kena palgeid Pilwerünkad palistawad, Palistawad kulla karwa, Silitawad siidi narma. ', 'Poeg. ',
         'kas tunned pilwe pöues Sala peiteliku sisu. ',
         'Pike wälgud, müristused,  Röhutawad raheterad, Lume paksud puistatused, Aikele ähwardused Magasiwad pilwe rüppes, Peteliku pöue peidus. ',
         'Kas ja tunned kulmu kastet, Langewada laugu wetta. ',
         'Röömu silmapilgu illu, Wiletsuse öhtu wilu Silma pisar sigitamas,  Kulmu kaste kosutamas. ',
         'Kergib jüda körgemale, Murrab mure meelekesta. ',
         'Warmalt weereb silmawesi, Kiirest kukkub kulmu kaste Töst-ja langmist tähändama. ',
         'Laulik lues lugusida, Weerewaida wärsisida. ',
         'Wöttab pihu wölsi wallast, Tüki teise tösi talust,  Kolmandama kuulu külast, Laenab lia meele laekat, Mötte möia magasista. ',
         'Näitab kueu kulla nägu, Köne kaunis töe karwa, Töe karwa, tarka arwu. ',
         'Sis on laulik osaw looja, Laitemata sönaeadja. ',
         'Kuulin Mardust kiljatama, Laane nurgas nuttemaie,  Metsa kaius kaebamaie. ',
         'Mis ta kia kihutanud, Nuttu healta ärgatanud, Kaebamista kaswatanud, Ohkamista oimutanud. ',
         'Mardus leinab langu werda, Langu werda, häda ärda, Pinatuse piaraida, Kurnatuse kustutuli. ',
         'Mis on taewas tarretanud,  Pilweid pilul palistanud. ',
         'Ohtu kate katab kaugelt, Mure waipa matab musta, Peidab pilwe pimedase Lauliku pääwa terada. ',
         'Waimu warjud udupilwes, Kaste hölma kergitusel, Argel jammul astunessa Näitwad werist wöitlemista, Mäsamiste mööga mängt,  Tapja taperi tantisi, Söa aege surma suitsu, Nälja pölwe närtsimisi, Katku kurnatuse jälgi, Toowad kurbe teaduida, Ohtupäiwist ohkamisi, Pinatuste piaraida. ',
         'Isa maa ilu hoieldes, Wööraste wasta wöideldes Warisesid waprad wallad, Kolletasid kihelkonnad Muiste pölwe mulla alla. ',
         'Nende pina pigistused, Nende waewa wäsimused, Muiste kallid mälestused Kostku meile kustumata. ',
         'Taewas, wana taadi talus, Taaralaiste targas seltsis Istusiwad kanged mehed, Wöörsil wahwad wöidumehed Tulepaistel paeatelles Ennemuistet ilmumisi. ',
         'Kalewi poeg, kangelane, Kuulus meesi kuningliku, Istus nende keskeela, Kuulas käsi pösakülle Laulikute lugusida, Kandlelööja kituida. ',
         'Misga tema teguida, Jumedaida juhatusid, Ilmas ilmund imedui, Tugewaida toimetui, Mis ta elu pölwes teinud, Enne jurma jobitanud Maha jäänud jälgi mööda, Järel jäänud risme raeal Tulepaistel paeatati, Kulla keelil kuulutati. ',
         'Kül jaan jönu jeadlemaie, Kulda lönga kedramaie, Höbe eideid korutama, Waske wärtnaid weeretama, Kui hakkan kuuldu kuduma, Nägusida näitamaie, Teguida tunnistama, Luguida lahutama. ',
         'Waata. ',
         'laanes puie peidus, Puie peidus, pöösa warjus, Lepa leina hölma alla, Kurbtuskase kate alla  Seijab seie kalmu küngast, Seite sammeldanud ängi, Seite küngast, sörwad lag und Kellei kaswa kohendajat, Söbraliku jeadejada, Walwal silmil wahtisida, Ornal armul kaitsejaida. ',
         'Üks on ängi häda ohu, Teine ängi orja kütkes, Kolmas sängi öa kurnas, |  Neljas ängi nälja pinas, Wies ängi wilets pölwes, Kues sängi katku surmas, Seitsmes Tautsi tappe sängi. ',
         'Seep je Eesti muiste pöli Enne Wene walitsuse Armu tiwa kaitsemista. ',
         'Juhtud önne juhatusel, Hallijate healitsusel, Marduskutsu meelitusel  Sina eitsme künka juure, Sammeldanud ängidele. ',
         'Istuta, poeg. ',
         'isa illuks, Isa illuks pöösakete, Ema illuks önnelille, Orjawita öele illuks, Wislapuuda wenna liuks, Toominga tutawa önneks. ',
         'Tippi taimed targal kombel, Pista juured mulla pöue,  Sibli häästijügawale, Et naad kaunistkaswamaie, Oigel aeal öit emaie Läheksid rüngaste röömuks, Uinusängidele illuks, Murupinnale tugeka, Magajate mälestuseks. ',
         'Mis seal uinub muru ölmas, Waikes pörmu rüppes puhkab. ',
         'Muru ölma, mulla rüppe,  Pörmu pöue peitewale Maeti meie mälestused, Muiste pölwe pärandued, Muiste önne öilmekesed, Muiste jöna sünnitused, Muiste laulu lunastued. ',
         'Alea emalikus kaius Warjab unustuse waipa, Katab kawaluse kuube, Sögedate söna söba. ',
         ' Mis jeal katkud kooletanud, Pina pihid pigistanud, Möllaw mööka magatanud, Surma sängi uigutanud, Udu ölma uinutanud. ',
         'ükskord, kui ma noor weel olin, Noor weel olin, norkus seisin, Kergel jalal karjas käisin, Wainul kurni weeretasin, Külakigel öötsutasin,  Uinusin ma une ikes, Ööteliste tulepaistel Pöösa warjul puhkamaie, Jaani linna ligidale. ',
         'Waat. ',
         'mis imelikud illud, Kogemata kuldsed kueud Arkasiwad unenäuka Suikuwale silma ette, Waimu waate wärawile. ',
         'Waprad mehed, wanad targad,  Lustilised laulu loojad, Kulla kandle kölksutajad, Kenad kähärpääga pigad Kargasiwad kesk öö pidul Kalmu künkilt köpsatelles Uduwarjus hüppamaie. ',
         'Astusiwad argel jammul, Argel jammul, kergel kannul Libiedes ligemale, Tähändasid ala tähtil,  Pilgutasid silma pilul. ',
         'Uinuta meid magamaie. ', 'Uinuge, unustud loomad, Puhkage, kolletand kueud. ',
         'Uinuge kuldasta unda, Kunni teid paremal pääwal Kenama hommiku koitu Taara toas äralab uuest. ',
         'Noored mehed, mehina poead, Wiruja Järwamaa wösud, Arju armamad öed, Pärnu paremad piigad, Lääne lähämad langud, Kuulge, oh kuulge mu könet. ',
         'Kaugema pääwade kueud, Warema aegade warjud, Endine önne ja illu, Muistene kurbtus ja mure, Muistene kuldane köne, Muistene lauliku lugu Meelta mulle mölgutamas, Palgesida paiutamas. ',
         'Kuulge jutusi, jumedaid, Kalewide kuulutusi, Alewide awaldusi, Olewide ilmutusi, Sulewide sünnitusi. ',
         'Mis mulpuiskand pihlakasta, Tullnud teised toomingasta, Taara tamme tüwikusta, Wanat ölmitud sönasta, Wanat juurdunud jutusta, Wanemuinese wöösta, Jutta hiukse algusta. ',
         'Mis sealt rismeid rijusin, Jälgilt kokku koristasin Laulu löngaka kedrasin, Löuendiksa löksutasin, Kalewi kangaka kuduin. ',
         '–age DoKalewi poeg. ',
         'Sau, laulik, lausa juuga, Söua laulu laewakesta, Paeataja paadikesta Söua neid jenna kaldale, Kuhu kotkad kulda jönu, Kaarnad höbe kuulutui, Luiked waskleid lunastusi Wanast aeast waristanud, Muiste päiwist pillutanud. ',
         'Teadanege, linnud targad, Wilistage, wette laened, Awaldage, tuuled, armsad. ',
         'Kusse Kalewide kätki, Kange meeste kodupaika, Wikerlaste warjuwalda. ',
         'Laula, laulik, miks ei laula, Miks ei, kulla. ', 'kuulutele. ',
         'Mis ma kukkun, kurwa lindu, Misma laulan, närt sind nokka. ',
         'Noorus närtsinud nömmessa, Kolletanud kanarpiku, Leinakase lehtedela. ',
         'Enne, kui önnes höiskasin, Pääwa paistel a’asin pilli, Höbedasi laulu löimeid Kulda kangaka kudusin, Nägin mönda naljakaida Salaliku sündimisi, Imeliku ilmutusi. ',
         'Tuule ema töstis tiba, Marumemme murdis meta, Sundis laened söitemaie, Merel laial mängimaie, Puistas pilwed pögenema, Pögenema Pike pakku. ',
         'Waataldes röömu rünkalta Päikese palge peale Mötlin muiste mälestusi, Wanal aeal sündind asju. ',
         'Jooske jöudsamalt, jögedad, Tulge, künsad, tunnistama, Metsad märku andemaie, Salgud, jala jönaldama. ',
         'Lausa töuseb laulu illu Kui je päike pilwe paisust, Aeab meele ärkamaie, Mötted lustil mölkumaie. ',
         'Kaugelt nään koda kaswama, Kalewide kalju linna, Tammed müüridel tugika, Kalju rahnud seina katteks, Toomingad toa tahaje. ',
         'Minu körwa kostab kohin Langewa mere laenesta, Köikumata kaljukünkast, Mis jäid marust murdemata, Tuulehoot tuiskamata, Wihmaweesta weeremata. ',
         'Sahkageme sönasida Wanajutu jälgedele, Raudse pölwe radadele. ',
         'Muiste leiti Kalewa las Kangemeeste kausida Mitmes külas kaswamaies, Mitmes talus töusemaies, Mis kui Taaralaiste taimed, Wöidulaiste wösukesed Sureliku eide jülest Seie ilma siginenud. ',
         'Kut mina hakkan kuulutama, Laulu joada laskemaie, Wana lugu weeretama. ',
         'Ei mind jöua ohjad hoida, Ohjad hoida, köied köita, Pilwed pika ei pidada, Taewas laia tallitseda. ',
         'Külad jääwad kuulamaie, Möiad mötteid märkamaie, Sakiad parwil sei amaie, Linnad eemalt luurimaie. ',
         'Elu oli noorel löunel, Keskepääwa keeritusel Kalewide kaajakesta Sugul rohkeit digitanud. ',
         'Linda oli laulusuuga Wiburidwa wibutelles Kangeid poegi kaswatanud Isa kueu kandejaksa, Oli anderohkel rinnal, Eide armu allikala Kaelakandjaks kojutanud, Inimeseks imetanud, Kuude walgel taadi rinnal Kangelaseks karastanud, Möistelikuks muijutanud. ',
         'Kunni asja a’ajaks kaswid, Sammu lühendajaks saiwad. ',
         'Poegist taadi ela öhtul Kaki alles kodu kaswid, Kaks kui herne kaunakesta. ',
         'Teiled olid tuulejuhil, Linmuteede tähändusel Wööramaale rada wötnud,. ', 'Käiki pika kauguela',
         'Läinud önne otsimaie, Pesa aset püüdemaie',
         'Ega meie kitsik kohta, Ahtral lüpsil pöllumaada Wöind ei köiki kaswatada, Toitu neile toimetada, Pääwarju walmistada, Keha katet soetada. ',
         'Kalewtaati oli käskind, Kindlal jönal kinnitanud. ',
         'Meie maada markamata ühe poea päranduseks, Walitjuse wallaks jätta. ',
         'Ehk kül poead perekaupa Isa suuruseks sirguid, Tükaltie tugewusel Wötnud osa taadi wöimust. ',
         'Siski silmanähtawalta Oites ia olemine,  Meelemöistus, märkamine Rohkemalt kui"teiste külles Wimsel sündind wösukesel. ',
         'Kes kui kallim pesamuna, Abielu äbariku, Hilja pärast ia surma Weeres pääwa walguele. ',
         'Praegu jälgi wiimsest poeast, Mälestuse märkisida Laial mitmes kohas leida. ',
         'Paigutie paeatakse Sohni nimé rahwa suusa Wimse wösukee kohta. ', 'Ehk kül suurem Eesti sugu Kolmas lugu. ',
         'Pualise pääwa paistel Istus mere kalda ääres Kalewide. ',
         'noorem poega, Waatas laente lustimängt, Wette woode weeremista Kerge tuule keeritusel. ',
         'Akiliste ähwardelles Puistas musta pilwe pöuest Tuule hoogu tuiskamaie, Pani laened paisumaie, Kohisedes kerkimaie. ',
         'Aike öitis rauda sillal Waske ratusil wankriga, Tuiskas tulda tulleesa. ', 'Sädemeida söitenessa. ',
         'Pikker taati pöruteles Kärinada käidanessa, Wiskas wälku wäledaste. ',
         'Kurjad waimud kohkunessa Kuulsid karistaja heale, Pögenesid Pike pakku Laie mere laenetesse. ', 'Hüüdes. ',
         'Aike, haiutele. ', 'Pikker, pista nina p–. ',
         'Hüppasiwad körgelt kaldalt Kukerpalli mere pöhja, Wahtus wette woodiesa',
         'Kalewide poega kargas Nende jälgil laenetesse, Langes kotka kirusela Kurjalaiste kaela peale. ',
         'Püüdis neid kui wähke urkat Kauni kaelakoti täie. ', 'Mere pinda töusenesa. ',
         'Ujus kangelase poega Tüki kalda ligemale, Paiskas kotist kurjalaisi Wöimal wiskel kalda peale Pike rauda wita alla, Kus neid puruks kolgitie, Hundi roaks hukkatie. ',
         'Kalewide wennikeled Läinud kodunt kolmekeste Lustil meta luusimaie. ',
         'Eit oli jäänud üksinessa Koeu kirstu kaitsejaks, Warakambri warjajaks, Taalderi toale tugika. ',
         'Eit pani paea tulele, Keetis rooga poegadele, Kohendas tulda korrale, Kaites tule kibemeida, Et ei leeke peaseks lakke, Kirg ei lennaks katukele. ',
         'Ni on ölgirinna seadus, Leekuningana kohus. ',
         'Kalewide noored poead Läinud meta luusimaie, Linnu jälgei aeama, Karu jälgi otsimaie, Pödra jälgi püüdemaie, Metshärga waatamaie, Metakrimu kiujamaie. ',
         'Karu oli kaeras käinud, Mesipuiel wöörsis olnud, Pödra nähtud pöllu ääres. ',
         'Kukku, kägu, kulda lindu, Healitsele, höbenoka, Weeretele, waskikeeli. ',
         'Kukku meile kuulutusi, Healitsele ilmutusi, Weeretele lauluwara, Kedra kuulutuse lönga. ',
         'Kui ei kukku, kukkun ise, Paeatelen pardikene, Lasen luige laulusida, Seitsmekordseid jönumida Wanast aeast weeremaie. ',
         'üks on jönum ülge suusta, Teine latente tüterilta, Kolmas ranna kaljudelta, Neljas näkki neidudelta, Wies wette emandalta, Kues kuude kudujalta, Seitsmes saare taadi suusta, Saare eide mälestustest. ',
         'Kalju einad kuulasiwad, Laened laiad luurisiwad, Tähteilmad tunnistasid. ',
         'Kuida Kalewide poega Julgelt eide jälgesida, Tedre kadund teedesida Hobuta läks otsimaie, Täkuta läks tallamaie, Ilma ratsuta rändama. ',
         'Möni mees jääks mötlemaie, Möni naine nuttemaie, Möni piga pisaraila, Kui naad Kalewide poega Suure mere öudemiel, Keskel laea laeneida, Kalewi poeg. ',
         ' Wahtus wette woodiesa ükipäine ööde peitus Sala teel jaaks silmamaie. ',
         'Kui ei kaldalt silma sihti, Silma sihti, waate woli Kujagilta jälgi kannnd, Teedrerada tähändanud. ',
         'Kargas noormees körgeelta Kaldajörwalt laenetesse, Woode laia woodiese, Kohijewa wettesängi. ',
         'Sundis käsi söudemaie, Tagant jalgu tüürimaie, Pääs hiuksid purjetama. ',
         'Söudis kirelt Soome poole, Tüürideles Turja poole, Purjeteles pöhja poole. ',
         'Tötas eite tabamaie, Tedre paelust peastamaie, Lindat lingut aitamaie. ',
         'Soowis Soome tuuslarida, Tuuletarka tuuseldama, Wargaküünit wemmeldama, Rööwelida rookimaie, Et ei enam naiste rööwi, Neitsi wargel wörgutusi Seie ilma sigineke. ',
         'Wana wanker, Rootsi karu, Pöhjanaele, tähte poega, Juhatasid siraw silmil Taewa alta teede rada Miniale mere laentel, Näitasiwad nisket teeda, Märga rada Soome maale, Körge kaljuranna poole. ',
         'Juba hommikune puna, Koi du ettekuulutaja Taewa palgeid palistamas',
         'Juba sirendawad tähed Koidu pirel kahwatamas. ',
         'Ju ehk laulis Looja kukke Ue pääwa ukse juusa, Köörutelles taadi kana Walgue öue wärawal. ',
         'Kalewi poeg, kangelane, Wette wode weeretusel, Laia laente langutuel Ueub Soome ranna poole. ',
         'Tugew käsi löhkus laeneid, Pekis laeneid merepinnal. ',
         'Kigutawa wettekätki Weereteles wirku meesta, Usinada ueujada Langutawa laente turjal Kaugemale pöhja poole, Kaljuranna kallastele. ',
         'Koi du heledama kuma Paneb merda punetama, Mere laeneid lökendama. ',
         'Juba paistab kaugeelta Soome kaljukünklik randa, Kerkib ika körgemale Silmawaatel sei amaie. ',
         'Tugew käsi löhkus laeneid, Peki laeneid merepinnal. ',
         'Kigutawa wettekätki Weereteles wirku meesta, Usinada ueujada Langutawa laente turjal Kaugemale kalda poole. ',
         ' Ja kui pääwa lues walgus Koidu pihust lahti peasis, Teretelles terasida Taewasst hakkas külwamaie, Mis kui litrid merepinnal, Sitdilindid laenetele Weineidu ehitawad. ',
         'Jöudis Kalewide poega, Kangelaste kaswandiku Soomeranna kaldadele. ',
         'Istus wäsind wennikene Körge kalju rünka peale, Wetteweerul wints und likmeid Natukene puhkamaie. ',
         'Istus kalju rünka peale Wäsind keha karastama Hommikuse tuule öhul, Wette laenete wilula, Istus maha kalju peale Tülpind rammu toetama Jahutawal kaste jälgil, Mere karastawal aurul. ',
         'Soome tuuslar, tuuletarka, Oli paati randa jätnud, Lodjakesta ahelaga Kalju külgi kütkendanud, Et ei laente mängimine, Körgemate köikumine, Marutuule mäsamine Lootikut ei löhkunessa. ',
         'Laululinnud lustikeelil Töusnud päikest teretama. ',
         'Juba lHuke lööritelles Tallab kerget tuuleteda, Oöpik höiskab lepikusta. ',
         'Kalewi poeg, kange meesi, Seiis pääwa mure paelus, Kaki kurwastuse kütkes, Lese eide leinamitel. ',
         'Kolmandamal enne koitu, Wara enne walgeheta Hakkas koeu minemaie, Ranna poole rändamaie. ',
         'Tulid tuulet tuiatelles  Mönusamad möttekeed, Arkasiwad öhukesest Osawamad arwamied. ',
         'Soomes elas kuulus eppa Söarista jünnitaja, Waenurista walmistaja, Mönusama mööga meister. ',
         'Kalewi poeg paeatama. ',
         'Enne koeu minikuda Peaksin mööka muretsema,  Söasahka jobitama Waenlaste wastaseka. ',
         'Silmapilgul jammusida Teise teele seadanessa, Läks ta üle lagediku, Käis ta üle kanarpiku, Sammus läbi ambla joosta, Rändas tüki raba sooda',
         'Seal tulli wasta meta suuri, Wasta lausa laane meta. ',
         ' Kalewide kange poega Eksis mööda männi meta, Eksis pääwa, eksis kaki, Kautas kolmandama pääwa Oige teede otsimisel. ',
         'Oö tulli pika ja pimeda,. ', ' Taewas täheta ja tume. ', 'Otis meesi önne kaupa, Katsus teede käsidela. ',
         'Kalewida kalim poega Langes laia kuuse alla Pikaliste muru peale Pahatueul paeatelles. ',
         'Köik nüüd kullad lähwad koeu, Höbedajed hoonetesse, Teiled tutawa talude. ',
         'Minul kodu kole meta, Kamber keskel kuusikuda, Laia laane minu tuba, Tuules on mul tule ase, Wihmas wihlemie paika, Udus uinumie kohta. ',
         'Isa läks ju enne ilmast, Kui sain pääwa paistusela, Eite langes jurma sängi Sala söudikute jaatel Ilma et mu silmad nägid, Jättis mind waeseks järele. ',
         'Wennad kaugel Wirudela, Teised Turgi raeadela. ',
         'Jäin kui lagle laenetele, Pardi poega parwe ääre, Kotkas körgele kaljule, üksi ilma elamaie. ',
         'Teile pääwa töusikula Kalewi poeg köndimaie, Hüwa önne öpetusel Uest teeda otsimaie',
         'Räästas hüüdis rägästikust, Kägu kukkus kuuse otsast. ',
         'äike paistis puie ladwil, htu ölal rippaküle, Wäsind warjud wenitasid Waikuswaipa üle muru, Rahu rüüdi metadele. ',
         'Leinakase lehtiskaitut Muretisaawa rüpesta, Kuuse kulda kübarasta. ',
         'Hüüdis üksik laululindu  Pääwa löpetuse lugu, Hüüdis öhtu wiludusel Loojalkitutilumelles Tänu targema taadile. ',
         'Kalewi poeg, kangelane, Kui oli peasnud unepaelust, Wäsimuse woliduselt, Hakkas silmi seletelles, Laugusida lahutelles Arwamisi arutama,  Tahtis meele tuletada, Mööda läinud mälestada. ',
         'Mis kui närt sind unenägu, Kolletanud kueukene Tema luulemies läikis. ',
         'Wimse aea jammu atmed Polnud selget jälge jätnud. ',
         'Sügieses udu sompus, Pöualises pilwe suitsus Seisid eilsed jündimited. ',
         ' Kas ta Soomes, ehk kas Saares Pika lustisi pidanud, Kas tal Turgist tulnud tüli, Taplust olnud Tuura raeal. ',
         'Sest ei teadnud tema selgest". ', 'Sepa poea jurmamine,. ',
         ' Waga were walamine Ei teind muretie mulju, Ega kahetsuse koormat. ',
         'Kallis Kalewide poega Töttas jälle töukamaie, Kiirel kihulrändamaie, Kunni küngas jöudis kätte, Kust ta tulles mööda käinud. ',
         'Köndis pääwa, köndis kaki Läbi laia lagedaida, Jöge mööda, mäge mööda, Läks siis laiast laanet läbi, Köndis tüki kolmat pääwa, Pikal jammul ranna poole. ',
         'Mere kaldal kalju külles, Kindlas ahelate kütkes Seisis tuuletarga lodja, Tuuslartaadi paadikene. ',
         'Kalewide poega wöttis Surmas angund sortsilase Paadikese päranduseks, Wöttis laewa lepituieks, Et ei olnud eite leidnud. ',
         'Kalewide kallim poega Peastis lahti paadikese Ahelate kütkendusest. ',
         'Istus ie lootsikusse, Wöttis mölad wöima kätte, Hakkas kirul aerumaie, Koeu poole püüdemaie, Pani purjed paisumaie, Rided tuulde rippumaie. ',
         'Tuule hoogu töukas tagant, Laene lükkas lustilikult Weeretelles Wiru poole. ',
         'Caewa küünal, ehatähte, Amariku selgem silma, Waata pilwe-lauge pilust, Taewa körge kulmu alta Lauliku teeradadele, Kandelniku käigi peale. ',
         'Waikselt waatas sinu silma Muiste pölwe muudendusi, Waatas Taara tammikuida, Hiepuida, illujaida, Haljendawas leh tede ehtes. ',
         'Waatas Ema laente läiki Päikese paistwal palgel. ',
         'Waatas Ema woolamista, Kohisewat woode käiki Talwe rinnalta wöördudes. ',
         'Kül ja, kallis tähetütar, Taewa piga peenikene, Nägid wendi weeremaie, Kui nad läksid liisku heitma. ',
         'Külap nägid künnimeesta, Kuningliku Kalewida. ',
         'Wiru pöldu winderiku, Järwa pöldu jänderiku Kange käega kündemaie. ',
         'Kui ta kündis juured jaared, Suured jaared, körged künkad, Kordas laiad lagedikud, Soosa pilliroogustikud, Mäed wagude wahele, Künkad küürul pöllu peale, Orud körguste keskele. ',
         'Kül ja kallis tähte piga, Kangelase kündi nägid. ', 'Kui mul peaks ehk puudumaie. ', 'Laulikuie löngasida,. ',
         'Korutud kulda könesi, Höbekedre eiekesi, Külap tähte näitab teeda, Taewas tarka radasida. ',
         'Kui mul puudub siis weel jönnt. ',
         'Weel jäid koeu koti täied, Ahju peale kinda täied, Parsile weel pihutäied, Kirstu kingakanna täied. ',
         'Kui mul weel peaks puudumaie. ',
         'Külap korjan kanarpikut, Nopin raatma raeadelta, Rijun lija rägastikust, Kolletanud heina kulust, Korjan kasteheinakejest, Hädaliku körrekestet, Aarun kokku haganikust, Kölgastiku pühkmetesta. ',
         'Kui ma lugu luuletama, Hakkan lausa laulamaie, Kalewida kuulutama. ',
         'Siis jääb walda waatamaie, Küla kulda kuulamaie, Sakiad erwi sei amaie, Möia hulgad mötlemaie, Kuulama minu könesi, Minu laulu löktatusi. ',
         'Tuleb taga targem aega, Parem pidu meie pölwe. ',
         'Siis ma laulan muiste laulud, Löksutan lauliku lugud, Weeretelen wanad wisid, Mis ma Arjusta arwasin, Mis ma Wirusta wedasin, Misma Läänest lunastasin, Taara hiesta tabasin. ',
         'Päike seiis peale löune Weeru poole wenitelles Langel puie ladwadele. ',
         'Kalewide kallim poega Arkas unet ehmatelles. ',
         'Kuri unenäu kueu Hädaohtu ähwardelles Wöitis mehe wäsimuse. ',
         'Lehe wöimul wilistelles Hakkas hobu hüüdemaie, Künni ruuna kutsumaie. ',
         'Wile waus waikuesse, Kutsumine kustus kaugel Tuiskel laial tuuledesse. ',
         'Hobu ei kuulnud hüüdemist, Kallis ruun ei mehe kutsu. ', 'Linnu keele lustilikult Höiskas wasta hüüdemista. ',
         'Kalewide kange poega Töttas hobu tabamaie. ',
         'Ratsu jälgil rändadeles Kammitatmel käidanese Köndis üle kanarpiku Tüki teeda, palju maada, Ladus laiu lagedaida, Sammus piki ambla jooda, Kunni wasta jöudis kohta, Kuhu ruuna kikjatele, Hüwa hobu huntidele Roaks oli roidunenud, Surma sülle suikenenud. ',
         'Töteliku tunnistähti, Mitmetwärki märkiida Leidis laialt lagedalta. ', 'Leidis närt sind hobu naha,. ',
         'Ruuna raswa rismeida, Leidis laia were loigu, Leidis maka muru pealta, Leidis luida ligimailta, Kohtelt külle kontisida, Leidis ligi lepikuda Surnud ratsu sisikonmad, Pörna tükid pöösastikust. ',
         'Sestap jai ta selget märki, Kuda ruunakene koolnud, Hobu surmassa suikunud. ',
         'Kalewide kange poega, Kuijai kahju kahetienud, Onnetusta ohke puhkel Tüki aega tuulutanud, Wötis kadund ratsu kue Mättalt kaaja mälestuseks. ',
         'Suures wihas pai und süda Süttis mehel pölemaie. ', 'Sisap seadis täie juuga Sönasida söudewale. ',
         'Seija waiki, tuule wuhin, Kuule, waiki, meta kohin. ',
         'Seiske, ladwad, öudemata, Körrekesed, köikumata, Lehekesed, liikumata. ',
         'Senni kui jönu saeatan, Kurjemaida kukutelen, Wihasemaid weeretelen. ',
         'Saagu, jaagu, ma jaeatan, Saagu tejuguna jurema, Mätta otta mädanema, Nurme peale nälgamaie, Pöösa alla pendimaie. ',
         'Kena ööde küünlakene, Walgusssilmil taewa wahti. ',
         'Laena lusti laulikule Radasida rändamaie, Sala teesi jammumaie. ',
         'Kussa Kalev enne käinud, Poega enne puhkanenud, Söbradega seltsitelles Mönda tempu toimetanud, Imelista ilmutanud. ',
         'Sirawade täh tede silmad Tunnistanud nende teesi, Kaugel maadel käikisida. ',
         'Näinud, mis seal naja tehti Wiru kuuskede wilula, Harju haawade wahela, Lääne lepiku keskela, Näinud meeste naljatusi, Wie wiletsuse waewa, Kue kiutatuse kütke, Seitsme jammu sidemede Kogemata kinnitusta, Kuhu mehed kukkusiwad, Lustipidul lange siwad. ',
         'Läki aga laaneese, Pööastiku paksudese Laulusida lunastama Kuldaida koristama, Höbedasi oimaie, Waskesida wötemaie. ',
         'Ni aga kuulin kuulutui, Wana jutu juurdumisi, Muiste lölmitud sönasi, Kullal kedratud könesi. ',
         'Kalewide kange poega. ', 'Läinud hobu ostemaie, Künni ruuna kauplemaie',
         'Kui ta käinud tüki teeda, Tüki teeda, palju maada, Laulis lindu lepikusta, Tarka lindu tammikusta, Kägu kulda kuusikusta. ',
         'Hobu hirnub Hiu-maalta, Sälgu karjub suuret joosta, Warsa karjub kaugeelta. ',
         'Hobu hirnub ostajada, Sälgu karjub adulada, Warsa walgeid waljaida. ',
         'Tänu teile, linnud targad, Tänu teede juhtidele',
         'Paeatab Kalewi poega, Töstab jalga teise teele Kirel käigil jammumaie',
         'Wiis oli Wirus wibimisi, Harjus aea witemisi, Järwas tühja tallitusi, Kust ei jaanud kaugemale. ',
         'Paharäti poegadele Töusnud tuulet tülidusi, Tühjast rahu rikumisi. ',
         'Järweke, kus enne eland, Kaksipäini muidu käinud, Läinud kitsaks kadeduses, Weikeks wihadule waenus. ',
         'Poissidel ei olnud püsi, Mehikestel enam mahti, Pidid perest pögenema Uuta aset otsimaie. ',
         'Amariku palge puna Palisteles pilweida Wikeliste wirulieks, Kullakarwa keerulieks Ue pääwa iluduseks, Kuiju Kalewide poega Arkal silmil asemelta Kargas ülesköndimaie. ',
         'Wirgul "pole wibimista, Kiirel kuskil köheldusta. ',
         'Karastawa kasteela Sammusida sirutelles Köndis kange mehe poega Pärast wöetud linmupetet Peipe järwe ranna poole. ',
         'Löhkus wööda metasida, Ule laiu lagedaida, Läbi paksu pöösastiku, Siis weel tüki amblasooda, Möne tüki mättastiku, Kuhu teed ei olnud tehtud, Rada ette raeatatud. ',
         'Kus ta tormas laane kandu, Senna tänaw sigiuesa, Kus ta tötkus sooda mööda, Kaewandiku kaswatasi, Kus ta köndis künkeliku, Sile jammul jündinessa. ',
         'Künkad läksid küürusele, Madalamaks mönda mägi, Kuhu kanda kauemine, Warwas juhtus wiibimaie. ',
         'Järwe ääre jöudanese Wibis Kalev waatamaie, Kas ei kuskilt koorma kandjaks Parajada paadikesta, Lodja juhtuks leidamaie. ',
         ' Langetawa laenetele Silmi kaugel sirutelles "Polnud näha paadisesta, Lodja kuskil ligemalta. ',
         'Kalev kääris kue ölmad Woltis wöö wahedele, Sisap suisa jammumaie, Laentest läbi löhkumaie. ',
         'Waatakid ja, wennikene, Kalda äärest tema käiki, Lennus köndi laenetessa, Nääks ei noorem nugissilma Koguniste teista kallast, Kuhu mees wöiks kuiwikule Kanda jälle kinnitada, Warbilt wetta walgutada. ',
         'Kalewide kange poega Pidand ei tee pikuesta, Wesirada ränkuesta Sammudele sidujaida. ',
         'Löhkus aga lustilikult Lahkel meelel laenesida, Tuiskas wetta tolmamaie, Körgeele kerkimaie, Walges wahtus wihiema. ',
         'Kalad pöhjas kohkuliwad, Wähid urkas wabileid, Lagled läksid laente alla, Pardid pakku pilliroogu Mehe jammu müdinala. ',
         'Kese oleks kogemata Sellel pääwal juhtund senna Se kül oleks omal silmil Wöinud näha wöörikuida Sala asju jündimaie, Imeliku ilmumaie. ',
         'Kui oleks körgelt kaljudelta Joa wahtus woolanenud, Pilwepaksult piiskajida Uduaurus puistand orgu, Kihiedes laente kerki Walgel wahul weeretanud Mere poole minemaie. ',
         'Ehk kui raskem rahepilwe Aikele ähwardusel Päikese palgeid peitnud. ',
         'Nönda murdwad metapaksut Waenlase wennikeled Kalewide kaela peale, Kesse koormat kandanessa Rahul teedekäiki rändab. ',
         'Kui ja weristatud karu, Matsu jaanud metsalie Nägid jahi näpistusel, Surmapina pigistusel Küti peale kippumaie, Sisap wöib ehk, wennikene, Möttes meeletuletada, Wöid ehk lugu werandila, Asja poolilt arwadella. ',
         'Kuida Kalewide poega Nurjatumaid nuthlemaie, Tontisida tonkimaie, Waenlaji sai wirutama. ',
         'Läkkijägil lagedale Waeuutüli waatamaie, Kuulutusi kuulamaie, Wanapölwe wagudelta Laulusönu lunastama, Kuhu kotkanokad kulda Kanarpiku kaswatanud,. ',
         ' Lagedale lahutanud, Haned haljast höbedada Wetteela walgustanud. ',
         'Kalewide kallis poega Kui oli käinud tüki teeda Lauakoorem öladela, Kaelakotis kasupoisi, Weike mehikene warjul. ',
         'Kes kui wähki urkanessa Unekaius uinunessa Maguaste magamaie. ',
         'Kalev metsat läbi käies Murdnud kepiks männikese, Tugiks pädaja tüwiku. ',
         'See ei olnud köige juurem, Ega wähem weikematet. ',
         'Kui oli ladwa katkendanud, Tüki wötnud tüwikusta, Paistis kepikese pikus Kümme sülda körgutie, Paari jala paksutie. ',
         'Wemmal mehe wääraline Wöis, kui kogemata waenu Kuskilt tuleks kiujamaie, Abimeheks astuneda. ',
         'Mööga kombel pidi malka Kiuseliku metjakoeri, Kiskehambil kutsikaida Teelta ära törjutama. ',
         'Metapaksust mörtsukana Lendsid kolm meet lagedale Koormakandjat kiujamaie. ',
         'Peipe sortsilase poead, Tulehargi abimehed, Keda ia kihutanud. ',
         'Ööde wilulönnistanud, Sealap astus ängiela Peipe joolaiortsilane, Kes ei wöinud Kalewida Walwel silmil wangistada. ',
         'Peipe tuuslar jönatarka, Mönes tükis Mana tarka, Püüdis unepaelutuel, Wäsimuse wörgutuel Kangelasta kimbatada. ',
         ' Pani söle söudemaie, Arpu aga aerumaie, Kaarnakiwi keeramaie. ',
         'Sönajala sortsisunnil Kurje sönu kandemaie. ',
         'Wöttis unerohtusida, Wäsitaja wösukesi, Sölmis rohud sortsisönal, Pistis kimbus pähitele Kalewi poea ängi otsa. ',
         ' Misga pikad unepaelad Kanget meesta kütkendasid. ',
         'Peipe tuuslar, jönatarka, Kui sai tembud toimetanud, Kawalused katsutanud, Kirustelles kandasida Pistis pakku pögenema. ',
         'Oö. ',
         'jöudis, päike töusis, Päike weeres, öhtu söudis Uestööda ömblemaie,  Kordamiste keeritusel Wananaia seaduela. ',
         'Kallis Kalewide poega Lebas sängis likumata. ',
         'Wirut olid Willandisse Kiruskäud käidanenud, Alewide söber noori, Kalewide kannupoisi, Juhatelles jälgi mööda Rutuskäud Peipe randa,  Kuda käskn enne kuulnud. ',
         'Aga kiruskäsukandjad Kuningast ei leidnud rannas. ', 'Oö. ',
         'jöudis, päike töusis, Päike weeres, öhtu söudis Uestööda ömblemaie, Kordamiste keeritusel Wanaia seaduela. ',
         'Pääwad kaswid nädal pikaks, Wenisid ööd selle wörraks. ', ' Kallis Kalewide poega Lebas sängis liikumata. ',
         'Kenam suwe ilu pääwa, Onnerikas röömupidu Kutus rahwast kaugeelta Taaramäele mängimaie, Laia lusti laskemaie. ',
         'Laewad tulid Ema laenel Lustil wette weeretusel Peipserannast Taara paika. ',
         ' Wirust, Järwalt, Harjust, Läänest Langes rahwast ligemale, Aga keski kuningada Neit ei olnud silmal näinud, Ega wöinud tema jälgi Tulles kuskilt tunnistada. ',
         'Oö. ',
         'jöudis, päike töusis, Päike weeres, öhtu söudis Uestööda ömblemaie, Kordamiste keeritusel  Wanaia seaduela. ',
         'Kuuka pääwad kaswasiwad, Wenis kuudeks ööde waikus. ',
         'Kalewide kallis poega Lebas sängis liikumata, Uinus önnetumat unda. ',
         'Juba suwe öilme illu Närtsind poolil nurmedela, Kalewide kallis poega Suikus unerohu sunnil  Sortsisöna sidemetes, Kui üks petis unenägu Onnelt tuli äratama, Wöimust meesta wirgutama. ',
         'Unenägu näitas naja, Kuida ue möögatera Paremaste paenutati, Walusamastwalmistati, Köwemamaks karastati, Tugewamaks tautati. ',
         'Enne sül olin esimene Külawainul kilkamaies, Lindu laulu laskemaies, Sönasida seademaies, Esimene laulumeesi Wärsisida weeretamas. ',
         'Laulin üksi lusti pärast, Laulin kaki katjudeles Wöidu wasta waldaida. ',
         'Laulin, et kaljud kargasid, Metsad mütates mürasid, Mere laened löhkenesid, Pilwed pikil käriesid, Tuule kohin healta kohkus. ',
         'Ei nüüd wäeti enam jaksa, Heal ei anna hella wili, Jöud ei kanna kanget wili, Sörm ei paenu kandelila. ',
         'Olen wanaka waarunud, Rammetumaka rauganud. ',
         'Kalewide kuulutelles Arkab noorus öitsemaie, Kallim aega kaswamaie, Kus ma enne kulda kägu, Höbedana öue lindu Kodu kopelis kukkusin, Meie metades elkisin. ',
         'Juba mina mullu laulin, Toonamullu murrin keele, Aasta jönu autasin, Teise taga tautasin, Kolmanda keerutasin, Neljandal kokkusidusin. ',
         'Kalewide kange poega, Kui oli käiki löpetanud,. ',
         ' Pääwatööda toimetanud, Töttas jälle öhtu eela Senna enne tehtud sängi, Kus ta kalli mööga kautand. ',
         'Enne kui heitis puhkama, Wäsimusta waigistama, Wöttis ängil öhtuheinet. ',
         'Soolasorts ei näitnud silma, Polnud näha poegatida. ',
         'Woisid weel ehk uöiawihtel Muhkusida muiutada, Haawatud kehaarstida. ',
         'Hommikula enna koitu, Wara enne walgeela. ', 'Kargas Kalev kirusela Koeu poole köndimaie. ',
         'Täna tallas teista teeda, Rändas uusi radasida Söudwal jammul kaugemale. ',
         'Mööda sood ja mööda raba, Kus ei muud kui hunti käinud, Metsa pakut pöösastikult Puges kangelase poega Wirgult läbi Wiru poole. ',
         'Sammusida sirutelles Kadusiwad koormakandjal Jöudsalt pikad penikoormad. ',
         'Ega olnud enne öhtud Mehel palju puhkamista. ',
         'Wat kui päike allaweeres, Ladus tema laualaju Olapenmilt pöösa alla. ',
         'Puhkas wäsind pihtasida, Wöttis keha karastuseks Leiwakotist lijadusta. ', "Ei oln'd jüdant sülle wötta. ",
         'Läksin koeu leinadese, Uke ette nutedesja. ', 'Taati minulta küsima, Eite asja nöudemaie. ',
         'Miks ja nutad, poega noori. ', 'Miks ja kurdad kewadele. ',
         'Mis ma nutan, taadikene, Mis ma kurdan, eidekene. ', 'Läksin lustil köndimaie,  Warasilta waatamaie. ',
         'Mis seal leidlin lepikusta, Kogemata kaasikusta. ',
         'Leidsin neiud neljakeste Madaraida kiskumaies, Puujuuri puistamaies, Turbasida tuhnimaies. ',
         'Pääd walged, pösed punased, Sitikmustad silmakulmud. ',
         "Ei ma julgend juurde minna,  Ei oln'd jüdant sülle wötta, Läksin koeu leinatesa. ",
         'Taati möistis, kostis wasta', 'Ole waita, poega noori. ', 'Kül panen ambu püüdemaie, Nooled pikad nopimaie. ',
         'Poega wastapaeatama', ',,Oh mu armas taadikene. ', 'Se pole ambu püüdemine, Ega nooli nopimine. ',
         ' Se on kulla ostemine, Höbeda lunastamine, Kallima kauba ostetawa. ',
         'Kül lähen linnat tooma kaupa, Poekambrist poordisida. ', 'Leti tagant lintisida, Seina pealta siidisida. ',
         'Seega petan neiukesed. ', '“Wölsin hobu hoielda, Ratsukesta rawitseda,  Körwikesta koutada',
         'Siis panjn ratsu rakkedele, Sammetie adulale, Höbedase helmetesse, Waskisele waljadele. ', 'Kalewi poeg. ',
         ' Läksin kaugelt kosimaie, Neiukesi otsimaie. ', 'Weerin teie wärawasse, Tulin teie ukte taha. ',
         'Neiu kuulis kamberisa, Laulis wasta lökutelles', 'Külapois, mul kulla wenda, Kaugelt tulnud kosilane. ',
         'Onne tunnil oled tulnud Piigakesta püüdemaie. ',
         'Peremees on kodunt läinud Asjasida aeamaie, Eite kooki küpsetamas, Laste leiba waalimaies, Ode noorem hanekarjas Lestajalgu lepitamas, Teine kulda küürimaies, Höbeasju haljastamas. ',
         'Mina üksi kurba lindu, Leinaikes löukene Wokil wärtnaid weeretamas, Kulda lönga kedramaies, Höbe eideid korutamas. ',
         'Kuule, kallis külapoisi, Petiskeelil peiukene. ',
         'Kasta oma käppasida Uke körwas ämberisse, Kussa märga tömmukarwa Tugewuse toetaja. ',
         'Siis ju käpal kaswab wöimu, Raudarammu rusikale, Misga kaljuseinad murrad, Löhud raudased wärawad, Terasiesta tehtud tornid. ',
         'Kui peab kangus kahanema, Liga rammu rammestama, Wöimus käesta wöördumaie. ',
         'Kasta käsi teise ämbri, Kussa märga pimakarwa Tugewuse taltataja, Kange wäe kustutaja. ',
         'Muidu tugew käsi murrab Pihuks köik, mis ettepuutub. ', 'Kalewide kange poega Töttas käsku täitemaie. ',
         'Piga kambrist palumaie. ', 'Kuule, kulla wennikene. ', 'Jäta mööka wötemata, Söarista Sarwikule. ',
         'Wöta paeuwitsakete, Wöta warjukaapekese. ', 'Paeuwita peastab pörgust, Kübar kurja kiutatuet. ',
         'Mööka wöid ja mönusama Sepal lasta jobitada,  Mööka oskab meister teha, Selli tarka sünnitada. ',
         'Aga kallist kaapekesta, Paeuwitsa wäetikesta Wöi ei ilmas kuskil leida. ',
         'Kübaral on kümme wäge, Wital eite jaladui, Ühekla weel ie woli. ',
         'Soowimiste öuendusel, Tahtemiste täitemijel  Witsakene wäga wägew, Kübar kangem abimeesi, Targem asja toimetaja. ',
         'Kalewide kange poega Möistis kohe, kostis wasta',
         'Külap jöuan soowimisi Tahtemijel tallitada Ilma sortsikübarata, Nöiawita aitamista. ',
         'Tuuslarite tuulesöidud,  Sortsilaste sünnitused, Tühja-taadi tembutused Saa ei meesta ekitama, Kangelasta kütkendama. ',
         'Tugewus teede tegija, Rammu radade raeaja. ',
         'Neitsikene noorukene Waidlemista waigistelles Wöttis kübara warnasta, Wöttis kätte kaapekeje,  Mis ei wildist wanutatud, Willast olnud walmistatud, Ega karwadet kogutud',
         'Kübar oli küüntelaastust, Korjakud küünte kildudelt. ', ' Targal kombel ietehtud. ',
         'Pigakene paeatelles Kübarada kiitemaie. ',
         'Seep je kübar makab kallis, Makab määratuma hinna, Kallima, kui kuning rigi, Set et teista sarnalista Suures ilmas pole jaada, Laial ilmal leidanessa. ',
         'Mis ja joowituste söudel, Igatsuste ihkamiel Jaliste himustakid. ',
         'Kaape kohe kaswatamas, Tahtemista täitemaies. ',
         'Nalja pärat pani neitsi Kaapekese oma pähä, Sönul ie joowimaie', 'Kaswa, kaswa, kulla neiu. ',
         'Sirgu, sirgu, sinisilma. ', 'Kaswa Kalewi körguseks, Sirgu söbra suuruseks. ',
         'Silmanähes sirgus ösar, Kaswis küündra, kaswis kaksi, Sirgus sülla, sirgus kaksi, Kaswis Kalewi körguseks, Sirgüs söbra suuruseks',
         'Kalewide kallis poega Neitsi naljamängi nähes, Kiireliste kaswamista, Silmapilgul sirgumista, Wöttis kaape piga päästa, Pani enda pähädani, Siisap soowil sönaldama. ',
         'Wau, Wau, wennikene. ', 'Kärssi, kärssi, kangemeesi. ',
         'Wau sülla weikemaka, Möne sülla madalamaks, Kärssi kokku keradela, Söstra noore jarnaliseks. ',
         'Kalev hakkas kahanema, Waus waka, waus kaksi, Kahanes weel möne küündra, Waus piga wääralieks, Sösarale jarnaliseks',
         'Oleks laulupoega noorem, Oleks, mis ta ennd olnud Kewadies kaunis illus, Suwe pire palistusel. ',
         'Siis ta laulaks pika pääwa, Laulaks läbi talwe öö, Laulaks naja ehk nädala, Kukkutelles poole kuuda Kalewide kaunist mängi Pörgupere piigadega, Laulaks, et metsad müraksid, Kaljud wasta kargeneksid. ',
         'Aga laulik, öhtukukke, Suwest lahkund luikekene, Pöörab silmad igatsedes Onnepääwa hommikule, Noorepölwe nurmedele, Kus weel kenadamad kirjad, Ilutamad önnelilled Röömuwaipa walmistasid. ',
         'Kus weel elu örnal rinnal Soemalt möni söbra süda Onnelikult wasta öhkas. ',
         'Kus weel kewadiel murul Külakige kergitusel Söstrasilmad söbralikult Heldusela hilgasiwad. ',
         'Milal jaab lauliku kewade Armul tagasitulema. ',
         'Töuse, laulu koidukene, Töuse kui je pääwatera Minu waimu silmadesse. ',
         'Paista muiste pölwe päiwi Amarusestärkamaie, Pilwepaksust paistemaie. ',
         'Kalewide kallil poeal Ei öit ilu jöge pidi, Mäng ei kullast mäge pidi',
         'Ilu oli pikal ööla Lustipidul löpemata, Mäng ei lasknud noorel mehel Aega minna igawaka, Ega nali neidudele Unesöba silmadele. ',
         'Oh kui ööl ei hirmutuseks Päikest tuleks paistemaie. ',
         'Nutis juba mitu noori Kadund armu kahetsedes, Kui ta sala löimesiidi Kangasjalgel kudutie',
         'Wana eite köögis wangis Istus kui löksus hiireke, Kust ei wöinud kasutütrid, Kalid minna keelamaie. ',
         'Teisel pääwal läksid piigad Kalewiga köndimaie, Läksid maea näitamaie, Warakambrid waatamaie. ',
         'Palged alles punetasid  Neitsidel weel naljatujet,  Misga öö neil önne mängil Lustilikult mööda läinud. ',
         'Nemad läksid kiwi uksest Körge kiwi wölwi alla, Köndisiwad kiwist teeda Tüki maada edasie. ',
         'Seal tuli wasta rikas tuba. ', 'Tuba oli rauast tehtud, Seina nurgad teraklesta, Rauda ukted, rauda aknad. ',
         'Kui mindkülad kuulessiwad, Möiad mötteid möistakiwad, Wallad wasta wötaksiwad, Mis ma laulus löksatelen, Siis ehk läheks möni lapsi Papisida palumaie, Muste kuubi kumardama. ',
         "Et nad heldest' wötaksiwad Laulukukke lunastada, Wihawaenust wabandada. ",
         'Kulid tulid kiskumaie, Kaarnad sulgi katkemaie, Kiriku akid kiutama. ',
         'Enne kui lapsi lagedale, Poeukene pääwapaiste, Wäeti weeres wainuele. ',
         'Need on karjalapse laulud Teupoiste trallikesed, Korrapiiga köörutused, Wanaeide wokilaulud, Targemate tahtemata, Suuremate sundimata, Körgemata käskimata. ',
         'Lapse lustid, lapse leinad, Noore nurme nukukesed Kewadise ehakueud, Widewiku wiitekeed. ',
         'Kallis Kalewide poega. ',
         'Kui oleks teadnud, wöinud teada, Mis sul jammu egamasse, Käiki tuleks kütkendama. ',
         'Ehk ja oleks enne jündi, Enne emast ilmumata Kartes juba läinud kaewu. ',
         'Laulik, kui ta lusti luhal Korra läinud köndimaie. ', 'Teelt ei enam taganema, Ega käigilt könverdama. ',
         'Penid meet ei aea pakku,  Koerad röömukäigilt meta. ',
         'Haugub Musta külamurult, Krantsikene karjamaalta, Tuku külatänawat. ',
         'Mees ei koeri meelitama, Kadedaid ei kartemaie. ',
         'Läki laulu luhadele, Kalewide küugastele, Alewide aasudele, Sulewide soode peale,  Neiukeste nurmedele Ilulilli noppimaie. ',
         'Kalewide kange poega Saand ei jada jammusida, Tuhat weel ei mööda teeda Koeu poole köndimaie, Kuiju kiusajate karja Kihutelles tema kannul Sammusida sölmimaies, Kiiretkäiki kütkendamas. ',
         ' Tühi taati tuldanessa Seitsmekümne ellidega Kalewida kiujamaie. ',
         'Tahtis kälimehe tüli, Sarwetaadi egadusta Mehepoeal ära maksta, Tuhatwörra taudella. ',
         'Noorem piiga peenikene Silmasida sirutelles Waenlasi waatanessa. ', 'Je niida healitsema. ',
         'Wibutele, nöiawitsa, Soowimista sigitama. ',
         'Moonda maa meredana, Luhad laial laeneteksa, Wösukesed wettewoodeks. ',
         'Ette silda sünnitele, Taha wetta weeretele. ', 'Silda ette söudijale, Kullakoorma kandejale. ',
         'Wetta taha waenlastele, Sarwik taadi ellidele. ',
         'Kuida piiga paeatanud, Warsti nöiawitsa wöimul Lugusida loodanessa, Lage merena laenetas, Wettewoosi weeretelles Tuulekigul kikumaie',
         'Kindel silda kandenesa Kuiwiljalgul Kalewida üle laia laenesida. ',
         'Sammu ette sündis silda, Kanna taha kaswis wesi Wahtu körgelwiatelles, Tühja poegi takistama, Kes kui kanad körgelt örrelt Mere kaldalt kahju nägid, Kuda kullikene küüsis Wärukese poea winud. ',
         ' Kulli siiski kinnitama, Tibadesta takistama Mehikeste nöu ei näitnud. ',
         'Sarwik taadi sellikesed Wöörast lugu waatamaie, Jekeskis imestama. ',
         'Kusap meri murudela, Laened tulnud lagedale. ', 'Wana tühi küimaie. ',
         'Kalewi poeg, kulla wenda,  Kas a wisid kodukanad, Tedrekesed meic toasta, Kasulapsed kamberista. ',
         'Kalev möistis, kostis wasta Pilkamiste. ', 'paeatelles', 'Witap wisin, wennikene,. ',
         ' Kogemata kodukanad, Tedrekesed teie toasta, Kasulapsed kamberista. ',
         'Wisin neiud walgeele,  Kudruskaelad kosjateele, Peiuratsu raeadele. ',
         'Tühi teistkord küsimaie, Kalewi poeg, kulla wenda, Kas ja wöitsid kälimehe Wöidumängil wainuela, Torkasid teda teibana Sömerliwa sei amaie, Sügawase sömerliwa',
         'Kalewi poeg kostis wasta Pilkamista paeatelles',
         'Külap wöitsin kälimehe Wöidumängil wainuela Torkasin teda teibana Kut kui kontisi ei murdnud Süüd ei mulle sündinegu. ',
         'Tühi jälle küsmaie, Pikemalta pärimaie',
         'Kalewi poeg, kulla wenda, Kas ja koogiküpetaja Wanaeide wangistasid, Lukutasid hiirelöksul Leiwakasti lebamaie. ',
         'Kalewide poega kostis Pilkamiste paeatelles',
         'Wisap panin, wennikene, Koogikese küpetaja Wanaeite wangiele, Lukutasin hire löksu Leiwakastile lebama, Ummuksesse undamaie, Kus, kui kirp ei ärgastanud, Memmekene praegu magab. ',
         'Tühi taati küimaie, Asja otsust aeamaie',
         'Kalewi poeg, kulla wenda, Kas ehk wötsid mööga warnat, Salamahti söasaha, Risusid Sarwiku raua. ',
         'Kalev möistis, kostis wasta, Pilkamiste paeatelles. ',
         'Kalewide kange poega Mötesida mölgutelles Alustanud arwamisi, Tarkus” teeda toimetada, Suure ilma otsa söita, Pöhja piirde purjetada Kus ei enne oldud käidud, Teed ei ette tehtanedud, Aga kuhu taewa kummi Maa külge kinnitatud. ',
         'Laskis laulu ladusaste, Sönaida öudewale. ',
         'Kui ma ratsul käidanema Halil lasen alla öue Sala teele öitemaie, Targa teele tallamaie, Lasen läbi lagediku, Läbi paksu pöösastiku, Murran üle mägedesta, Kargan kuristiku kaudu, Sammu tüki ambla sooda, Könnin teise kuiwistiku, Kolmandama kanarpiku, Neljandama nömmeida. ',
         'Sisap saaksin sihtis senna Järwed mul ei ölmiks jammu, Kui ei meri keelaks meesta. ',
         'Kuule kotkas, kaunis lindu. ',
         'Talita mind tilbadela ule wette weeremaie, Ule laente lendamaie, Senni kui ma ilma sörwa Käsidela katsumaie, Sörmila jaan jorkimaie, Kuhu taewa körge katus. ',
         ' Räästast maha raeatanud, Sinisidilseinaketed Aluspalka paigutanud. ',
         'Kuhu kuuja pääwakandja, Pilwete ülespidaja Oma kanda kinnitanud, Warbid maha wautanud. ',
         'Kui ta teadamata teesi Tahtis minna tallamaie, Suial päil jammumaie, Kuhu enne ükski käiki, Rada polnud raeatanud, Töstis healta tarka lindu, Kaarna söna kronkjuwale',
         'Kus ja silmad sini wetta, Laialisi laenesida, Kae, kas kaldal körkijaida, Wöhumööku wette ääres. ',
         'Parem jalg seal pörutagu Kange kanda wasta kallast. ',
         "Siis jaab maa sull' salasuuda, Warjul hoitud wärawada Laial lahti tegemaie, Kust jaad ilma ota kätte. ",
         'Kalewide poega kostis',
         'Eks ma ole önnekaupa Enne seda jadakorda Peipe järwest pelgamata, Wörtijärwest wankumata, Kaeu järwest kartemata, Lääne merest langemata, Koormaga ju läbi käinud. ',
         'Eks ma tunne nende teesi, Pikusmöödul piresida, Laente langu laiusida. ', 'Mis in kia kaswatanud. ',
         'Kalewide kallis poega, Kui oli taati teretanud, Lappu targaks tunnistanud,  Kohe otsust küimaie. ',
         'Kukkutele, wööras kägu, Laula, laula, linnukene, Wasta mulle, kulla wenda. ',
         'Kust je käiki kohemalta Sihil. ', 'ilma otja öuab. ',
         'Et ei teisi teedesida, Höbelöngal loogelista, Kuldalöngal keerulista Ette tuleks ekitama,  Käigil jammu kinnitama. ',
         'Juhata mind joonedele, Kuhu taewa kummikene Alla sörwa kinnitanud, Sinisidil einakei Lagedale langutanud, Kuhu kuu kustunessa, Päike läheb puhkamaie, Kui nad seatud wahikorda Oöl ja pääwal löppetanud. ',
         ' Kaarna kodu kuulutelli, Tarka lindu andis teada. ',
         'Kas ja silmad siniwetta, Laialisi laenesida, Kae, kas kaldal körkijaida, Wöhumööku wette ääres, Parem jalg seal pörutagu Kanget kanda wasta kallast. ',
         'Siis jaab maa sullsalasnuda, Warjul hoitud wärawid  Laial lahti tegemaie, Kust jaad ilma ota kätte. ',
         'Soowita mind senna sörwa Körkjakalda käidanema', 'Tarka kuulis, kostis wasta',
         'Sit ei töuse teedesida, Rändamie radasida Kujagilta ilma otsa. ',
         'Merela ei ole määra, Laenetele löpetusta  Seal, kus wana ia tarka Taewa katut kallutanud, Räästast maha raeatanud, Sinisidil einakei Lagedale langutanud. ',
         'Kese enne käidanenud Tühja tuuli tallamaies, Saiwad Sädemete jaarel Suure julguele surma. ',
         'odukaarna kuulutused  Tähendawad pörgu teeda, Wanapoisi wärawida. ',
         'Kui ja käiki kodumaale, Söber, joowid toimetada, Luban sulle lustipärast Teedejuhiks kaasa tulla. ',
         'Kalewide poega kostis', 'Koeu jöuan juhtimata Tuldud teeda teadawada. ',
         'Wöta waewaks, wennikene,  Wii mind wööra wainudele, Ilma ota ukse ette, Wana taadi wärawasse. ',
         'Lappu tarka küsimaie', 'Mis mullpalgaks pailatakse, Weuwaewaks wiatake. ', 'Kalewide poega kostis',
         'Mis ja soowid, söbrakene, Küsid hinda, kullakene. ', 'Peab sullpalgaks paiatama,  Weuwaewaks wiatama. ',
         'Wöta poole waranduse, Küsi kulda kümme kotti, Hüwa hulka höbedada. ',
         'Wii mind aga, wennikene, Ilma otsa ukte ette, Wana taadi wärawasse. ',
         'Mere sügawuse möödud, Pörgu pired pikkusela Neida tunnen nööridela. ',
         ' Suure ilma ota einad Tänini weel teadamata, Käsila mul katsumata. ', 'Lappu tarka laulis wasta',
         'Lia peale lustipärast, Pane palgaks peale hinna. ', 'Zeitseteistkümmes lugu. ',
         'Omerikas pölwekene Oites Eesti raeadelta, Rahukätki kigutelles Lahedaste lapsukesi Emalikus heldes kaius Seite suwe egamata, Seite talwe tautamata. ',
         'Olew oli, linnatarka, Kindlad kantid kaswatanud, Kaewandikud kohatanud, Nurgel tornid toetanud, Ilu-linna ehitanud Kalewi kalmu künkale, Isa sängi iluduseks, Helde memme mälestuseks. ',
         'Rahwast nähti rohkeeste, Peresida peakaste Warjupaika weeremaie. ',
         'Kes kui kanad kulli kühul Peituela pugesiwad Söasurma silma eesta, Häda ähwarduse eesta. ',
         'Kalewide kallis poega, Kogund rahwast kaedanessa Hüüdis. ',
         'linn peab Lindanija Memme mälestuseks jääma, Sest eks koht ei toida lapsi Rohkeste kui ema rinda“. ',
         'Alewide atmas poega Laskis teise linnakete Arju maale autada, Kesket jooda kaswatada Laanemetsa lagediku. ',
         'Sulewi poeg, jugulane, Asutelles Alutaha. ', ' Kolmandama kindla kohaWarjupaigaks waenu wasta. ',
         'Pika rahuliku pölwe, Oilmerikast önne aega Kipus jöda kurnamaie, Waenu wanker wautamaie. ',
         'Wiru randa weerenessa Söalaisi adandela, Tapejaida tuhandela, Pinajaida pilwendela, Keda kaugelt toonud tuuled, Wettewooded weeretanud. ',
         'Kiirekäsu kandijaida Lendes jammul Lindania Kuningale kuulutama, Et ju jöda öudemaies, Waenuwanker weeremaies. ',
         'Tule, tugew, tapemaie, Kange, waenlast kihutama. ',
         'Kalewide poega kargas Söaratsu adulasse, Tötas tuule tuhingila Wirgult Wiru raeadele Söa kära kustutama, Waenu wiha waigistama',
         'Wöttis kaaja wöidumehi, Kannupoisiks kangemaida. ',
         'Wiis kümmend Wiruusta, Kuuskümmend Kureiaarest, Seitlekümmend Soomeesta, Sada teisi jaarelaisi. ',
         'Kalewide kallis hobu Rahandela raksatelli, Kuldandela köliseli. ', 'Höbepäited paissid päästa. ',
         'Kasse kägu kukkub kurba, Linnukene laulab leina. ', ' Kurbtus jäägu kuusikusse, Leinamited lepikusse. ',
         'Kallis kange mehe poega. ',
         'Kui ja lähed teedekäiki, Surmateeda söitemaie, Ehita hobu elmessa, Ratsukene rahadese, Pane pähä. ',
         'kulda päited, Pane höbe pannaldessa, Pane siidi paeladesa. ',
         ' Siu siidi hobu silmad, Höbekarda ratsu kabjad, Pane lakka puna paela, Tukakete taalerisa, Saba siu ja jammetise. ',
         'Kalewi poeg, poisikene. ', 'Tahad minna taewa teeda. ',
         'Ara tähtissa takkista, Ara kuusa komistelle, Ara puutu päikesesse. ',
         'ko Jätta päikest paistemaie, Kuu kuma andemaie, Tähed teeda näitamaie. ', 'Kalewi poeg, poisikene. ',
         'Tahad minna pörgu teeda. ', 'Ara hukka pörgu ukted, Wärista pörgu wärawaid. ',
         'Jätta seisma pörgu seinad, Jätta uksed hukkamata, Wärawad wäristamata,  Seinad paigal sei amaie. ',
         'Lähed sötta öitemaie, Waenu teeda weeremaie. ',
         'Jätta nödrad nottimata, Poisikeled puutumata, Laste iad langemata. ',
         'Siis ei leski leinamaie, Piga silmi piaraila, Waesilapsi walu sisse. ',
         'Laulis lindu lepikusta,  Kukkus kägu kuusikusta, Hallia tütar aawikusta, Köerutelles koidukana',
         'Murueide tütred noored Lustipidu löpetama. ',
         'Kargasiwad körre pealta, Angerwaka warre pealta, Kurekatla pöhja pealta Kohkel koeu minemaie. ',
         'Juba eite töstis healta,  Juba kuri kutsumaies. ', 'Tulge pigad, peenikesed. ',
         'Tulge tööda toimetama, Sidisida sidumaie, Puna paelu punumaie, Juba laulid looja kukked, Laulid Ukko ukte pealta, Wana ia wärawalta. ',
         'Oekeled, ellakesed. ', 'Käigem kireste koduje. ', ' Otjas meie önne aasta, Löpetatud lustipidu. ',
         'Pöhla kotkas, kurja lindu, Laena tibu laulikule. ', 'Söudeid sönaeadijale Kergituseks kandelile. ',
         'Misga tuule tuisatusel, Maru mängi möllamiel Kalewide pörgukäiki, Salateede öudemista Tötelikult tähendellen. ',
         'Enne kui mul meele maalid, Kuuldud söna sünnitused Kaste pilwetese kauwad, Warju rüppe warisewad. ',
         'Wanemuine, laulutarka, Laie kulda löngakei, Höbedasi eiekesi Paeataja poolidele, Kuulutaja keradele. ',
         'Misga söna mängitelles Siledamaks siidiks sölmin, Kuldakirjal kangaks koon. ',
         'Endla piga, peenikene, Laena täna laulikule Walgustawa wörgukesta, Seletawa silmarätte. ',
         'Misga pörgu mälestused Ilutamaks ilmuksiwad, Elawamaks ärkakiwad. ',
         "Ööde pilwed palistawad Uduwörku walgus' wäljad, Kui ja jalga alla-ilma Pörgu piredele paned. ",
         'Kus ei pääwal paista päike, Kuu ei anna öösel kuma,. ', 'Täht ei tule teretama, Wirmalised walgust andma. ',
         'Koidu pirilt läikew päike Palistelles pilwetele Punetelles palgesida. ',
         'Linnukeeled lepikusta Tötasiwad trallitama, Lustilugu lööritama, Kägu kukkus kaasikusta, Pesilindu pöötastikust. ',
         'Wirgu, wirgu. ', 'wennikene. ',
         'Pääwa töusul töstis pääda Kallis Kalewide poega, Aeas keha istukille Kargas püsti kandadele, Suges hiuksid sörmendela, Harjutulles unda meta',
         'Wötis möne kulbi wörra Leemepaeast linmupettet Kange keha karastuseks. ',
         'Seltsimehed suikusiwad Kolmekeste koidu unda, Wenitasid wäsimusta, Ohtut walwamie waewa. ',
         'Kalewi poeg waatamaie Sündind lugu silmamaie, Kuhu öösel kellakandja Wennikene oli waunud. ',
         'Seal kus eile sinisuitjul Härjapölwelase pilweid Taewa näinud töusenesa, Silmas täna siniwetta, Laialisi laenesida Lagedale lahutatud, Naljakada korda näinud, Teab ehk asja arwaneda, Tegu ise tähendada. ',
         'Kuda Kalev pörgu koeri Oma kallalt kihutanud. ',
         'Kalewide kange poega, Kuhu matsu kukkutanud, Wopsukesta wautanud, Teista seal ei olnud tarwis. ',
         'Matsu mattis mehe maha, Wopsu tegi surma warju, Waigistelles waenumehe. ',
         'Natukese naja pärast Olid meestel tosud örrel, Kolmekümne kooljakehad Pörandale puistetatud. ',
         'Sarwik taati tagaseinast Hädapüsil hüüdemaie. ', 'Pea kinni, poisikene. ', 'Kui ja, jamps. ',
         'ei oska naja, Teeme tüli tötelikuks. ', 'Sest ei töusku mulle süüda, Mitte were wastamista. ',
         'Waras oled, wennikene, Oled rööwel riiumaie, Kes ja wööra wara käpad, Teise taskud tühendelled. ',
         'Waras oled, wargaks jääd ja, Rööwliks, rahwa ritujaka. ',
         'Ehk kas püüad waleks panna, Warga töösi wabandada. ', 'Kas ja pole kiskel küüsil Minu wara warastanud. ',
         'Kas ja wiimati ei winud Kalli soowikaapekese, Warastanud nöiawitsa,  Kannud kanad kamberista, Tedrekesed meie toasta. ',
         'Kas ja pole pikil küüsil Kiskund minu kullakerstud, Höbedajed häwitanud. ',
         'Minu mönusama mööka Pihus praegu paistanessa. ', 'Kelle kulda kellakene Sinu sörmes sädendeleb. ',
         'Kas ja, koer. ', 'ei ole kiskja,  Wöid ehk wargust wabandada. ',
         'Kalewi poeg möistis kohe, Kostis wasta kawalaste. ', 'Mis a mullist mulle meele, Toonamullit tuled tooma. ',
         'Suure suu södimited, Laia löuge löugutused Peeti wanast naistewisiks, Laste tüli lepitajaks. ',
         'Tuli meestel tülitusel Köwerusi kohendada, Seal ei olnud sönasolki, . ', '… Löualuie löksutusi. ',
         'Kangus pidi rammukatsel Waidlemista wahendama. ', 'Miks ja, wedel. ',
         'läksid meta, Murupöhja pakku urka Enne wöitlemie wöitu. ', 'Ohtu ölmal tulid, öenes. ',
         'Metjas mehi narrimaie, Härjapölwelase kueul Keedupada kiujamaie, Astu wälja ahju tagant, Käi ja kohe kamberista. ',
         'Lähme wälja lagedale Wiimatista wöidumängi Oigel kombel löpetama. ',
         'Selepärat seadsin jammud Pörgu teele tallamaie, Läksin kodunt köndimaie. ',
         'Et meil öigus ühe tasa, Kangus kaaluks ühe wörra. ', 'Tahan mööka pista tuppe, Wötta käästa kellakese. ',
         'Sedawisi sönaldelles Peastis kellakese paelust, Pistis tasku puhkamaie, Töukas mööka tuppeesa',
         ' Sarwik taati argel jammul Tuli kambrist kahwatanud, Lumiwalge üle läwe. ',
         'Ehmatusses eidepoea Meelemöistus mähkeesa, Et ei enam tunnud teeda Wanapöwe piredele Warienud wöitlemiste Järeljäänud jälgesida Pakemalt kui meie päiwil. ',
         'Siiski Kalewide käigilt Paistab kuipäike heledam Köigist kuuljam rammukate, Wöimsam wöitlemie mängi Pörgu peremehe talust. ',
         'Mets ja mägi märkasiwad, Kaljukünkad kuulasiwad, Sood ja rabad saiwad jöna, Wettelaened läkitusi. ',
         'Set et maapind müdinaga, Meri wahtus walgendates Tugewat tööd tunnistasid. ',
         'Wainuele walmistati Oue alla paras paika Rammukatsumie kohaks. ',
         'Wanal wisil wöttetie Käsidela niudet kinni, Wöeti püksi wärwelista Kümne küüne kangulega Keha wöimu katsudela. ',
         'Weri walgus küünte alla Sinipaisul sörmedesse. ',
         'Ehk kül wöimuwötew wesi, Närtsitawa kruusi märga Kurjal rammu kurnanessa, Wöinust wäga wäsiteles. ',
         'Kalewide kangel poeal Kahekordne kangus kaste Kehawöimu karastanud. ',
         'Siiski wältas wöitlemine, Meeste wöidumängimine Seite pääwa eisamata, Seite ööda löpemata, Enne kui naad selget otsust Wöitlemie wöidul saiwad. ',
         ' Sarwik taat kül alamahti Katsus kiusamie kombel Pöiki jalgel pilutada Kallist Kalewide poega, Kes kui tugew tamme tüwik, Raskem rauakiwi rahnu Kohalta ei komistanud. ',
         'Kordamiste kergitasid Teine teista töusemaie, Rabasiwad rakatelles  Mütta-mätta. ',
         'maha jälle, Mis kui Köu kärgatused Pöldusida pörutasid, Kaljusida köigutasid, Wetta tötsid wahtunessa. ',
         'Kalewide kawal poega Oskas ennast hoidaneda, Siuguela pealta sörmi, Angerjala alta sörmi Pörgulase pihust peasta. ',
         ' Koogus jalal kohe kanda Toeks wasta walmistada. ', 'Siski kippus kange wöimus Rammu wiimaks raugenema. ',
         'Eide wari walwjal silmil Nägi poea nörkemista, Wöttis käte woki koomla Keeritelles kümme korda Ule pää ümberpööri, Paiskas prantsti. ',
         'pörandale  Ettekueuks Kalewile, Sada waati walgus werda, Tuhat tündri töusis liha. ',
         'Kanged mehed kahekeste Ohtu oa wöttemaie, Kehasida karastama. ',
         'Kalewide kange poega Wautas wata rebewala, Köhtu kuhjal kerkimaie, Heitis maha muru peale Leiba luuse laskemaie. ',
         'Alewide poega moori Istus kulla kotidele, Höbedaste ölma peale, Warandusta walwamaie, Et ei rööwel rijumaie, Waras tuleks wöttemaie, Pikilsörmil puutumaie. ',
         'Kalewide kange poega Puhkas pörgu pahandusta, Wöitlemise wäsimusta, Rahakoorma rammestusta, Puhkas öö ja puhkas pääwa, Uinu sülles teise pääwa, Kolmanda kejkhommikuni. ',
         'Penikoorma kostis norin, Kostis hingamie körin, Mis kui hobukabja müdin Söa öitu üle silla Murupinda muljuteles, Puid ja pöösaid pöruteles. ',
         'Kolmandama pääwa keskel Tötasiwad mehed teele. ', 'Alewide armas poega Wöttis ühe koti kukla. ',
         'Kolm jäid koormaks Kalewile. ',
         'Kalewide kallis poega, Kese pärat pörgukäiki Mönda hüwa meie maale Kaulikuks kaswatanud, Elas ie Lindanias Seltsis oma söbradega. ',
         'Olew oli, linnatarka, Kolm weel linna ehitanud, Uhe linna löune alla, Teise linna töusu wasta, Kolmandama koidu alla. ',
         'Kut ai warju wanadele, Rahupaika raukadele. ',
         'Kalewide kallis poega Kulutanud koti kulda  Kolme linna asutuseks, Kolm weel warjul kamberisa Teiste tööde toimetuseks. ',
         'Söbrad seltsis sahkamaie, Kalewi poega palumaie. ', 'Wötta kruusid, wennikene. ',
         'Pane kihlad kotidese, Meelitused märssidese, Mine Kungla kosimaie Noorikuda nöudemaie. ',
         ' Kunglas kaswab kodukanu, Neitsikesi neljakeste. ',
         'Läki lindu püüdemaie Kopelista korjamaie, Lepikusta lingutama. ',
         'Kungla neitsid koowad kangast, Teewad kullast toimelista, Koowad höbelöngalista, Silitawad sidilista, Punuwad puna poogelist. ',
         'Kalewide poega möistis, Pilgeliste paeatama. ',
         'Läki linna tegemaie, Walisida walamaie, Kosjakambrit ehitama, Sidiängi seademaie. ',
         'Teeme linna lillekestet, Teeme tornid toomingasta, Walid ümber wahtarasta, Teeme toad tamme törust,  Kana munasta kamberid. ',
         'Et kui kaugelt käidanessa, Wöörad jääksid wahlimaie, Möistelikud mötlemaie, Targad lugu tunnistama. ',
         'Kelleks Kalev teinud linna, Kelleks ta walid walanud. ', 'Kalev teinud lustilinna, Kaswatanud kosjakambri,. ',
         '“Os im warjab waarikuida, Udukuube ümberkau du Kattab kahwatuse karwa Kuldse küngaste kueusi',
         'Merelaened murretake Kurwastuse krooksulieks, Päikese palgesida Peidab udupilwe paksu. ',
         'Wihiselleb wihma-hoogu, Raske rahe raksatelles Pöualise pöllu peale. ',
         'Kas ehk Kalewide kipi Kaljudela kölistelli, Ehk kas wereraske waenu Surma juba sünnitamas. ',
         'Laula, laula linmukeeli, Healitselle, höbenokka, Kulda kägu kuulutelle. ',
         'Mis seal kurba külwatie, Surmalista sünnitie. ',
         'Sügaw, waikne jurma orgu, Wereahne waenuwäli Korjab tuhandete kehad Pörmu pöue puhkamaie, Muru kaisu magamaie. ',
         'Kalewide kallis poega. ', 'Kas ja öhtu ölmadelta Tulid täna tumnistama Wimse wiletsuse wermeid. ',
         'Söudsid, söber, jönaldama, Aeakätkit awaldama Löpetuse lugusida. ',
         'Sind eiwöinud waenuwägt, Saand ei jöda suretama. ',
         'Kurwastuse kütkendused Wöitsid enne aegu wöimu, Soome sepa jajatused, Oma önnetumad jömad Mötlemata mööga kohta Saiwad sulle jurmajaksa. ',
         'Kui oli kuulnud söakäsku Kalewide kange poega, Wöind ei enam wiibineda Pikemalta pidudele. ',
         'Saatis ratsul jaadikuida Söamehi sundimaie, Kangemaida kirustama Waenu wasta walmistama. ',
         'Enne kui ta töttas teele, Alewile awaldama, Sulewile jönaldama. ',
         'Ega kulda kamberisa, Höbe kerstu kaane alla Waenus wargal wöttemata, Rööwli käpal riiumata. ',
         'Wiigem wara warju-urka Pörmu pöue peitewala, Kut ei waras käpamaie Ega rööwel risumaie. ',
         'Paistab parem päikene, Oitseb jälle önne aega. ', 'Wöttame wara wangista, Kullakoormad künka alta. ',
         'Siisap hauda sömerasePörgu pärijate poead,  Tagap selied tapjad',
         'Sahkes jedamaida jasis Wöltsiliku wöörakete Käsipidi kübarasta, Keeritelles tuulekiirul Ringis ümber raudalasta, Kui üht takku koonlakesta',
         'Kohin töusis tuuleöhku, Kui oleks kuri pöhjakotkas, Koleda öö sulgiskarja  Tuuletibu talllamaies. ',
         'Kalewi poeg rabas kätte, Paiskas maha pörgupoea Poolil rinnul mulla pöhja. ',
         'Sisap sasis teise söbra Käsipidi kaelukiesta, Keeritelles tuulekirul Ringis ümber raudalasta Kui üht takku koonlakesta. ',
         'Kohin töusis tuuleöhku,  Mühin laia laanemeta, Kui oleks maru möllamaies, Tulispaska tuiskamaies, Körgeid kuuski köigutamas, Pädajaida paenutamas, Tamme sida tantsitamas. ',
         'Kalewi poeg rabas kätte, Paiskas maha pörgupoea Poolil palgil mulla pöhja. ',
         'Siisap kolmandamast koerast  Käsipidi kukkalasta, Keeritelles tuulekirul Ringis ümber raudalasta Kui üht takku koonlakesta. ',
         'Kohin töusis tuuleöhku, Mühin laia laanemeta, Wuhin wettewoodeese Pragin piki pilwetesse. ',
         'Kui oleks söitmas raudasillal Waskirattasel wankerilla  Pikkertaati pörutelles, Aike äge ähwardamas. ',
         'Kalewi poeg rabas kätte, Paiskas maha pörgupoea, Mattis hoopis mulla alla. ',
         'Mulk jäi üki muru peale Kolmandamast kuulutama. ',
         'Teisel korral tuli targem Pettiskeelil poisikene Kalewi poega kiusama,  Keda rannast raudalajed Saatnud kaupa jobitama. ',
         'Kui ta kawaluse kombel Pikemalta paeatanud, Meikeelil meelitanud, Kostis Kalewide poega. ',
         'Miks meaega, mehikene, Wahendelles peame witma. ', 'Köht mul hakkab kutistelles Tühenduste tunnistama. ',
         ' Käi ja jöe kaldaale, Wötta wähiwarras wälja. ', 'Waata, pois. ', 'kas, wähkisida Sörgel palju ööda sülles. ',
         'Kui jaan köhtu kinnitanud, Tahan sulle targemalta Asjaotjust awaldada. ',
         'Raskel jammul raudalane Köndis jöe kaldaale Wähisaaki waatamaie,  Warrast wälja wöttamaie',
         'Kese kuulnud kentakamat, Näinud enne naljakamat, Kui siin silma sirgunesse. ',
         'Kalev oli kange käega Tömmand tükkis tüwikuga Pädaja puiet pikema, Pannud jeda sööda pideks, Wähiwardakeseks wette. ',
         'Rammetumal raudalasel  Polnud jöudu pädajada Laenetesta ligutada, Wähem warrast, wälja wötta. ',
         'Kalev ie käidanema Wiibimista waatamaie, Mis seal jöbral sammusida. ']
